name: "Jeep MQTT"
url: "https://github.com/msherga/Jeep-MQTT-Add-On"
description: "Connect your Uconnect car to Home Assistant. 🚗"
services:
    - "mqtt:want"
version: "CUSTOM"
homeassistant_api: true
#image: "ghcr.io/wubbl0rz/image-{arch}-fiat-champ"
slug: "jeep_mqtt"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""
  Brand: "Jeep"
  Region: "America"
  RefreshInterval: 15
  ConvertKmToMiles: false
  Debug: false
  AutoRefreshBattery: true
  AutoRefreshLocation: true
  EnableDangerousCommands: true
  CarUnknownLocation: "unknown"
  StartDelaySeconds: 1
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  Brand: list(Fiat|Ram|Jeep|Dodge|AlfaRomeo)
  Region: list(Europe|America)
  ConvertKmToMiles: bool
  RefreshInterval: int
  Debug: bool
  AutoRefreshBattery: bool
  AutoRefreshLocation: bool
  EnableDangerousCommands: bool
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
  CarUnknownLocation: str
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7
